title: Clarcky's Blog
author: Clarck G
email: clarckgahou@gmail.com
description: > # "Courage starts with showing up and letting ourselves be seen." 
Wanted to know what new or what is the trending news? Welcome, we will feed you with the latest and accurage information

# social links
twitter_username: Clarck Gahou
github_username:  Clarcky80

show_excerpts: true # set to false to remove excerpts on the homepage
